### ISSUE TITLE
Suggestion - dockerize the app

### ISSUE THREAD

**Issue by jeanphibaconnais** [thib1984/pypodo#11]
I think it's a good thing to dockerize the app 🙂

**Comment by jeanphibaconnais** [comment]
If you Want I can help you for this issue

**Comment by thib1984** [comment]
It's a good idea :)

**Comment by jeanphibaconnais** [comment]
it's make in this PR https://github.com/thib1984/pypodo/pull/20

**Comment by thib1984** [comment]
Perfect!
