### ISSUE TITLE
Add some unit test

### ISSUE THREAD

**Issue by bbougon** [thib1984/pypodo#15]
Add unit tests

**Comment by thib1984** [comment]
Yes, it is a very good idea to start unit tests! 
Can you init a PR ?

**Comment by bbougon** [comment]
I'm about to commit and push some unit tests:
- add TACHE ajoute une tâche
- del INDEX supprime une tâche
- list retourne vide
- list retourne une tâche
- list [tag] retourne une tâche avec un tag

So I have questions:
- for the tests to work, I had to change method signatures in order to provide open (and by default open is affected to open)
- I would have preferred to write golden tests but my knowledge of python is beginner (I will in a short future do that) 
- do you want me to write the tests in english?

**Comment by thib1984** [comment]
Thank you :)
Your first tests wille be very usefull!
I have a little problem because with the new color in logs the tests were KO. I have modifiied it little after the merge, can you see please?

**Comment by bbougon** [comment]
I was trying te resolve them :D but great you did it!
I check

**Comment by bbougon** [comment]
seems legit, I was struggling with the color assertion and stopped just before trying the carriet return, I see my guess was good.
In a future refacto, we should separate the display from the business and then mock the display for tests

**Comment by thib1984** [comment]
Yes, i think that the code should be refactor and clean. I supect a lot of anti patterns, and a python-developper 
would cry seeing the code... :)

**Comment by thib1984** [comment]
Hello @bbougon , i have found a "trick" to ignore color in the TU :

```
def escape_ansi(line):
    ansi_escape = re.compile(r'(?:\x1B[@-_]|[\x80-\x9F])[0-?]*[ -/]*[@-~]')
    return ansi_escape.sub('', line)
```
i will realize one TU for test the color

**Comment by bbougon** [comment]
sounds good!!

**Comment by thib1984** [comment]
With the @jeanphibaconnais job (docker image), i imagine a global golden test :)

**Comment by bbougon** [comment]
I just saw you added some new tests

**Comment by jeanphibaconnais** [comment]
We can use testcontainer which allow to test docker container. 
I have a first version of a dockerfile, I push a work in progress pull request, you are so impatient 😄

**Comment by bbougon** [comment]
the only thing with the golden test attached to the container is it looks more like an integration test which in these case I'm not sure it would have any benefit.
The idea is to be sure that first the golden test cover at best 100% of the app and then ease the refactoring part to be replaced by only unit test.
Maybe it's overkill to do it as the app is quite little for now and we may still fill the gap quite easily now we introduced unit test.
We can discuss over it tomorrow?

**Comment by thib1984** [comment]
Yes! In french perhaps. :D

**Comment by jeanphibaconnais** [comment]
I see one test for the docker version, it's about volume. Tomorrow I think be connect until 12'30 ans after 13h

**Comment by thib1984** [comment]
@bbougon with the mutation testing (you can see the readme to see the setup/configuration/commands), we can now improve the quality of our tests!
Are you interested by this challenge? :)

**Comment by thib1984** [comment]
80% of coverage and a big end-to-end smoke test
