### ISSUE TITLE
Index the tasks at deletion

### ISSUE THREAD

**Issue by bbougon** [thib1984/pypodo#17]
Actual result:
When deleting a task, the indexes of the other tasks stay as before.
```
['task1', 'task2', 'task3']
pypodo del 1
['task1', None , 'task3']
```

Expected result:
When deleting a task, the indexes are reindexed according to the new list
```
['task1', 'task2', 'task3']
pypodo del 1
['task1', 'task3']
```

**Comment by thib1984** [comment]
For my use, i can to chain two or more "pypodo del" without see "pypodo list".
On top of that, the implementation of the code will not be compatible with this issue.
However, i add a call to "pypodo list" in "pypodo sort". 

So, i "pause" this issue for the moment.

**Comment by thib1984** [comment]
Good news for you @bbougon :) This feature has been added in the last 2.3.0 version ;)
With the config file you can now activate the option of "autosort" by add 

```
[FONCTIONAL]
autosort = True
```

in a ~/.todo.rc

You can see details in th readme

**Comment by bbougon** [comment]
cool!!!!
