### ISSUE TITLE
backup folder

### ISSUE THREAD

**Issue by thib1984** [thib1984/pypodo#19]
do you want a backup folder to save/backup your .todo?
```
pypodo backup 
```
save ~/.todo_backup/.todo202010082025 with the content of the actual .todo

**Comment by isaacvv** [comment]
I will work on this. Can you assign to me?

**Comment by thib1984** [comment]
Ok :+1:

**Comment by thib1984** [comment]
@isaacvv It's working :) 
Thanks!
