### ISSUE TITLE
Docker conteneur a little slow

### ISSUE THREAD

**Issue by thib1984** [thib1984/pypodo#25]
```
~ ./time.sh "pypodo list" | tail -n 3
-----------------------------------------
 Exécution en 55 ms
-----------------------------------------
~ ./time.sh "docker run --mount type=bind,source=/home/itga9510/.todo,target=/root/.todo pypodo list" | tail -n 3
-----------------------------------------
 Exécution en 872 ms
-----------------------------------------
```
The pip app appears to be 20 times more fast the container :( 
Can we optimize the image? 

```
~ docker images | grep pypodo
pypodo                                       latest              efe7b8eaccdd        38 minutes ago      889MB
```

https://blog.alexis-hassler.com/2014/08/25/taille-images-docker.html
https://enix.io/fr/blog/cherie-j-ai-retreci-docker-part1/
https://stackoverflow.com/questions/48543834/how-do-i-reduce-a-python-docker-image-size-using-a-multi-stage-build

Perhaps can we use python:3.8-alpine?

@jeanphibaconnais are you interesting by this challenge?

**Comment by thib1984** [comment]
Aie...

~ ./time.sh "docker run hello-world" | tail -n3
-----------------------------------------
 Exécution en 800 ms
-----------------------------------------

**Comment by jeanphibaconnais** [comment]
Yes i can try but only Monday 🙂

**Comment by jeanphibaconnais** [comment]
Before change : 889MB
After modification, with alpine image : 58.4MB

**Comment by jeanphibaconnais** [comment]
But the execution time is not really good. Maybe a CLI command should be a good solution. The app is always turned on and users can write the command.

**Comment by thib1984** [comment]
I have found a alternate solution  @jeanphibaconnais 

~ ./time.sh "pypodo list" | tail -n 3
-----------------------------------------
 Exécution en 55 ms
-----------------------------------------
~ ./time.sh "docker run --mount type=bind,source=/home/itga9510/.todo,target=/root/.todo pypodo list" | tail -n 3
-----------------------------------------
 Exécution en 872 ms
-----------------------------------------
~ ./time.sh docker exec -ti pypododocker sh -c "pypodo list" | tail -n 3
-----------------------------------------
 Exécution en 230 ms
-----------------------------------------

```
#classic configuration
export PYPODO_FILE=<path of your pypodo file>
touch $PYPODO_FILE
export PYPODO_BACKUP=<path of your pypodo backup folder>
mkdir -p $PYPODO_BACKUP 
#run the pypodocontainer in sleep mode : one time only, at the first launch
docker run --d -rm --mount type=bind,source=${PYPODO_FILE},target=/root/.todo --mount type=bind,source=${PYPODO_BACKUP},target=/root/.todo_backup --entrypoint="sleep" pypodo43200


#so we have a container who is running and for dialog with it, for example
docker exec -ti pypododocker sh -c "pypodo list"
```

**Comment by thib1984** [comment]
i will test to write a shell script for this...

**Comment by thib1984** [comment]
Pushed in 2.0.1 -> 300ms for execution
