### ISSUE TITLE
.todo file deleted :(

### ISSUE THREAD

**Issue by thib1984** [thib1984/pypodo#32]
I have reproduced two or three times a .todo file deleted. It seems correlate to ci_cd (pip test? docker?) but i can't reproduce that.
Don't forget to backup your .todo file BEFORE develop new features!
@isaacvv  @bbougon @jeanphibaconnais
I update the readme file with this warning!

**Comment by bbougon** [comment]
weird, maybe  a test is using real fs while i am sure the one we wrote are
mocked.

**Comment by thib1984** [comment]
Hi,
non-reproducible and random... Nightmare...
I can launch a lot of times the ci_cd with or not errors... and at a moment... .todo is deleted

Never in a classic use.

**Comment by thib1984** [comment]
@bbougon 
I think that i've got it!
It's caused by random mutation testing (for the moment, the mutations are random), so one of test causes a delete of the real .todo file.
I search....

**Comment by thib1984** [comment]
OK, it's corected

```
# various checks on the todo file
def check(open = open):
	file_exists = os.path.isfile(STR_PATH_HOME__TODO_) 
	if file_exists:
		with open(STR_PATH_HOME__TODO_, 'r') as f:
			error = 'false'
			for line in f.readlines():
				# verification regex, index + task + possible tags
				if not re.findall("^\\d+ ([^#])+( #[^ #]+)*$",line.rstrip('\n')):
					print(colored("warning : this line has not a valid format in .todo - "+line.rstrip('\n'),"yellow"))
					error = 'true'
		if error == 'true':
			sys.exit(colored("error : verify the .todo file","red"))			
	else:
		open(STR_PATH_HOME__TODO_, "w")
		print(colored("info : creating .todolist file","green"))
```

the mutation who deletes the .todo file is the inversion of condition for 

```
if file_exists
```

And few functions who call check(), have not the parameter open.
@bbbougon, my bad, i think that i was not be attentive when i have refactor tests.

Sorry!
