### ISSUE TITLE
mock_open and os.path.exists

### ISSUE THREAD

**Issue by thib1984** [thib1984/pypodo#39]
It seems that 

``os.path.exists(STR_PATH_HOME__TODO_)`` tests the real file EVEN IF i use ``new_callable=mock_open + read data`` in my test file...
@bbougon do you have idea how correct that?

**Comment by bbougon** [comment]
i guess you have to mock os.path.exists either like we did for sys.arg
either like mock_open

**Comment by thib1984** [comment]
It's done, thanks @bbougon

**Comment by bbougon** [comment]
welcome ;)
Bertrand Bougon
