### ISSUE TITLE
Need help for unit test backup 

### ISSUE THREAD

**Issue by thib1984** [thib1984/pypodo#43]
@bbougon , are you OK for construct the tests about the "pypodo backup"?
We can see the coverage to measure the quality of the tests.

**Comment by bbougon** [comment]
i can do that tomorrow or friday :D

Bertrand Bougon

**Comment by thib1984** [comment]
Amazing :+1: 

![image](https://user-images.githubusercontent.com/45128847/96349919-e361e980-10b2-11eb-9e81-1a68eb30a5a3.png)

**Comment by bbougon** [comment]
👍😉
